spring:
  application:
    name: api_gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084

zuul:
  routes:
    myproject:
      path: /myproject/**
      serviceId: project
    #简洁写法
    project: /myproject/**
